# Generated by Django 3.1.2 on 2020-11-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='title_beginner',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title_description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title_progress',
        ),
    ]
